#Persistent Volume Claim - PVC is a request for storage by a user. 
#Similar to a pod. Pods consume node resources and PVCs consume PV resources
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi