#Service - An abstract way to expose an application running on a set of Pods as a network service.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:   # We dont need to worry about converting to base64
  MYSQL_USER: cm9vdA==     # root
  MYSQL_PASSWORD: cGFzc3dvcmQ= #password
